import { uuid, integer, pgTable, text } from "drizzle-orm/pg-core";

export * from "./auth-schema";
import { users } from "./auth-schema";

export const tabs = pgTable("tabs", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  // uuid v4 id generated by the client
  clientId: uuid("client_id").notNull(),
  userId: text("user_id").references(() => users.id),

  name: text("name"),
});
