tabWidth: 4
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
jsxSingleQuote: false
trailingComma: es5
bracketSpacing: true
bracketSameLine: false
arrowParens: avoid
endOfLine: lf
embeddedLanguageFormatting: auto
singleAttributePerLine: false
