name: Deploy server to Cloud Run
on:
  workflow_call:
    inputs:
      github_env:
        required: true
        type: string
    secrets:
      GOOGLE_SERVICE_ACCOUNT:
        required: true
      MONGODB_CONNECTION_STRING:
        required: true
jobs:
  server_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_env }}
    steps:
      - uses: 'actions/checkout@v3'
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          username: _json_key
          password: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          registry: '${{ vars.GAR_LOCATION }}-docker.pkg.dev'

      - name: Use buildx driver
        run: docker buildx create --use

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GAR_ID }}/${{ vars.CLOUD_RUN_SERVICE }}:${{ github.sha }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - uses: 'google-github-actions/deploy-cloudrun@v1'
        with:
          service: '${{ vars.CLOUD_RUN_SERVICE }}'
          region: '${{ vars.CLOUD_RUN_REGION }}'
          image: '${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.GOOGLE_PROJECT_ID }}/${{ vars.GAR_ID }}/${{ vars.CLOUD_RUN_SERVICE }}:${{ github.sha }}'
          env_vars: |
            MONGODB_CONNECTION=${{ secrets.MONGODB_CONNECTION_STRING }}
            CLOUD_STORAGE_BUCKET=${{ vars.CLOUD_STORAGE_BUCKET }}
            CLOUD_STORAGE_SUBPATH=${{ vars.CLOUD_STORAGE_SUBPATH }}
