name: Run development server deploy on dev merge
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - server/**/*.*
jobs:
  run:
    uses: ./.github/workflows/cloudrun-server-deploy.yml
    with:
      github_env: development
