name: Run development website deploy on dev merge
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - website/**/*.*
jobs:
  run:
    uses: ./.github/workflows/firebase-hosting-website-deploy.yml
    with:
      github_env: development
    secrets:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
