name: Run development website deploy on dev merge
on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - website/**/*.*
jobs:
  run:
    uses: ./.github/workflows/firebase-hosting-website-deploy.yml@dev
    with:
      github_env: development
