name: Deploy Websites to firebase hosting
on:
  workflow_call:
jobs:
  website_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cd website && npm install && npm run build
        env:
          VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}
          VITE_LINKS_BASE_URL: ${{ vars.LINKS_BASE_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}'
          channelId: '${{ vars.FIREBASE_CHANNEL_ID }}'
          projectId: '${{ vars.GOOGLE_PROJECT_ID }}'
          entryPoint: website
