name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
    paths:
      - website/**/*.*
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - run: cd website && npm install && npm run build
        env:
          VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}
          VITE_LINKS_BASE_URL: ${{ vars.LINKS_BASE_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GOOGLE_SERVICE_ACCOUNT }}'
          channelId: '${{ vars.FIREBASE_CHANNEL_ID }}'
          projectId: '${{ vars.GOOGLE_PROJECT_ID }}'
          entryPoint: website
