name: Deploy Websites to firebase hosting
on:
  workflow_call:
    inputs:
      github_env:
        required: true
        type: string
    secrets:
      GOOGLE_SERVICE_ACCOUNT:
        required: true
jobs:
  website_deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.github_env }}
    steps:
      - uses: actions/checkout@v3

      - run: cd website && npm install && npm run build
        env:
          VITE_API_BASE_URL: ${{ vars.API_BASE_URL }}
          VITE_LINKS_BASE_URL: ${{ vars.LINKS_BASE_URL }}
          VITE_FILES_BASE_URL: ${{ vars.FILES_BASE_URL }}

      - name: Replace firebase config
        run: awk '{
             sub(/#HOSTING_TARGET#/,"${{ vars.FIREBASE_HOSTING_TARGET }}");
             sub(/#CLOUD_RUN_SERVICE_ID#/,"${{ vars.CLOUD_RUN_SERVICE }}");
             sub(/#CLOUD_RUN_REGION#/,"${{ vars.CLOUD_RUN_REGION }}");
             sub(/#FILE_BUCKET_URL#/,"${{ vars.FILE_BUCKET_URL }}");
             print > "website/firebase.json"
            }' website/firebase.json

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          channelId: ${{ vars.FIREBASE_CHANNEL_ID }}
          projectId: ${{ vars.GOOGLE_PROJECT_ID }}
          target: ${{ vars.FIREBASE_HOSTING_TARGET }}
          entryPoint: website
