name: Run production server deploy on main merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - server/**/*.*
jobs:
  run:
    uses: ./.github/workflows/cloudrun-server-deploy.yml
    with:
      github_env: production
