name: Run production website deploy on main merge
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - website/**/*.*
jobs:
  run:
    uses: ./.github/workflows/firebase-hosting-website-deploy.yml
    with:
      github_env: production
    secrets:
      GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
